spring:
  application:
    name: MYALBUM-ZIPKIN
  boot:
    admin:
      client:
        url: http://47.106.199.167:8084
        instance:
          health-url: http://39.105.167.236:9411
          service-url: http://39.105.167.236:9411
          management-url: http://39.105.167.236:9411

server:
  port: 9411

eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://47.106.199.167:8761/eureka/

  instance:
    hostname: 39.105.137.236
    # 优先使用IP地址方式进行注册服务
#    prefer-ip-address: true
    # 配置使用指定IP
    ip-address: 39.105.137.236
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoint:
    health:
      show-details: always