spring:
  application:
    name: MYALBUM-ADMIN-SERVER
  zipkin:
    base-url: http://47.106.199.167:9411

server:
  port: 8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 注意：此处在视频里是 include: ["health", "info"] 但已无效了，请修改
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.106.199.167:8761/eureka/
  instance:
    hostname: 47.106.199.167
    #    # 优先使用IP地址方式进行注册服务
    #    prefer-ip-address: true
    # 配置使用指定IP
    ip-address: 47.106.199.167
    instance-id:  ${eureka.instance.hostname}:${server.port}