spring:
  application:
    name: MYALBUM-REGISTER  #myalbum-service-register
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    time-zone: GMT+8 #时区加8
    default-property-inclusion: non_null  #屏蔽掉为null的字段

  rabbitmq:
    username: email
    password: email
    host: 39.105.137.236
#  zipkin:
#    base-url: http://localhost:9411
#  boot:
#    admin:
#      client:
#        url: http://localhost:8084
server:
  port: 10020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: 127.0.0.1
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true
    # 配置使用指定IP
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.hostname}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env #必须排除env文件
feign:
  hystrix:
    enabled: true
