spring:
  application:
    name: MYALBUM-REGISTER  #myalbum-service-register
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    time-zone: GMT+8 #时区加8
    default-property-inclusion: non_null  #屏蔽掉为null的字段

  rabbitmq:
    username: email
    password: email
    host: 39.105.137.236

  zipkin:
    base-url: http://39.105.137.236:9411
  boot:
    admin:
      client:
        url: http://47.106.199.167:8084
        instance:
          health-url: http://39.105.137.236:10020/actuator/info
          service-url: http://39.105.137.236:10020
server:
  port: 10020

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.106.199.167:8761/eureka/
  instance:
    hostname: 39.105.137.236
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true
    # 配置使用指定IP
    ip-address: 39.105.137.236
    instance-id: ${eureka.instance.hostname}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env #必须排除env文件
feign:
  hystrix:
    enabled: true

#全局配置
# 请求连接的超时时间 默认的时间为 1 秒
ribbon:
  ReadTimeout: 15000 #获取或设置读取操作未完成时发生超时之前的毫秒数
  ConnectTimeout: 15000 #客户端等待与服务器建立连接的时间（以毫秒计）
#  MaxAutoRetries: 1  #在同一台服务器上重试的最大次数
#  MaxAutoRetriesNextServer: 2 #要重试的下一个服务器的最大数量
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 7200000 #断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试。

#白名单设置
security_whitelist: /**
