spring:
  application:
    name: myalbum-zipkin


server:
  port: 9411

eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://39.105.137.236:8761/eureka/

  instance:
    hostname: 47.106.199.167
    # 优先使用IP地址方式进行注册服务
#    prefer-ip-address: true
    # 配置使用指定IP
    ip-address: 47.106.199.167
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}

management:
  metrics:
    web:
      server:
        auto-time-requests: false