spring:
  application:
    name: myalbum-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: 127.0.0.1
#    # 优先使用IP地址方式进行注册服务
#    prefer-ip-address: true
    # 配置使用指定IP
    ip-address: 127.0.0.1
    instance-id:  ${eureka.instance.hostname}:${server.port}


management:
  metrics:
    web:
      server:
        auto-time-requests: false