server:
  port: 10060
spring:
  application:
    name: myalbum-service-linux
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  zipkin:
    base-url: http://47.106.199.167:9411
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    time-zone: GMT+8 #时区加8
    default-property-inclusion: non_null  #屏蔽掉为null的字段
  freemarker:
    suffix: html

management:
  endpoints:
    web:
      exposure:
        include: "*"
#security:
#  oauth2:
#    resource:
#      id: mydemo-service-provider-test
#      user-info-uri: http://47.106.199.167:10000/auth/auth/user
#      prefer-token-info: false
logging:
  level:
    cn:
      yan_wm:
        myalbum: INFO

