spring:
  zipkin:
    base-url: http://47.106.199.167:9411
  redis:
    database: 0
    host: 118.89.190.234
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  application:
    name: myalbum-service-security-oauth2
  datasource:
    druid:
      url: jdbc:mysql://47.106.199.167:3306/myalbum_oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Ab123$%^
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 118.89.190.234:8848
        ip: 47.106.199.167
    sentinel:
      transport:
        port: 8719
        dashboard: 118.89.190.234:8080

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    time-zone: GMT+8 #时区加8
    default-property-inclusion: non_null  #屏蔽掉为null的字段

server:
  port: 10010

mybatis:
  type-aliases-package: cn.yan_wm.myalbum.commons.domain
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true