spring:
  application:
    name: MYALBM-USER  #myalbum-service-provider-user
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    time-zone: GMT+8 #时区加8
    default-property-inclusion: non_null  #屏蔽掉为null的字段
  datasource:
    druid:
      url: jdbc:mysql://47.106.199.167:3306/myalbum_resource?useUnicode=true&characterEncoding=utf-8&useSSL=false&&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: Ab123$%^
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true #打印执行的sql语句
    hibernate:
      ddl-auto: none # 第一次建表create  后面用update,要不然每次重启都会新建表
    properties:
      hibernate:
        format_sql: false
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #设置数据库方言  记住必须要使用 MySQL5InnoDBDialect 指定数据库类型对应InnoDB  ;如果使用MySQLDialect 则对应的是MyISAM
  zipkin:
    base-url: http://39.105.137.236:9411
  boot:
    admin:
      client:
        url: http://47.106.199.167:8084
        instance:
          health-url: http://101.132.139.17:10200/actuator/info
          service-url: http://101.132.139.17:10200

server:
  port: 10200

eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://47.106.199.167:8761/eureka/
  instance:
    hostname: 101.132.139.17
    # 配置使用指定IP
    ip-address: 101.132.139.17
    instance-id: ${eureka.instance.hostname}:${server.port}

mybatis:
  type-aliases-package: cn.yan_wm.myalbum.commons.domain
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env #必须排除env文件

logging:
  level:
    cn.yan_wm.myalbum.service.provider.user.mapper: debug

#白名单设置
security_whitelist: /abc