spring:
  application:
    name: MYALBUM-SERVICE-PROVIDER-BACKSTAGE
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    time-zone: GMT+8 #时区加8
    default-property-inclusion: non_null  #屏蔽掉为null的字段
  datasource:
    druid:
      url: jdbc:mysql://47.106.199.167:3306/myalbum_oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Ab123$%^
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  zipkin:
    base-url: http://39.105.137.236:9411
  boot:
    admin:
      client:
        url: http://47.106.199.167:8084
        instance:
          health-url: http://101.132.139.17:10100/actuator/info
          service-url: http://101.132.139.17:10100

server:
  port: 10100

mybatis:
  type-aliases-package: cn.yan_wm.myalbum.commons.domain
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env #必须排除env文件

eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://47.106.199.167:8761/eureka/
  instance:
    hostname: 101.132.139.17
    # 配置使用指定IP
    ip-address: 101.132.139.17
    instance-id: ${eureka.instance.hostname}:${server.port}