#spring:
#  profiles:
#    active: dev
#
#config-server-host: 47.106.199.167
#spring-protive-active: prod
#spring:
#  cloud:
#    config:
#      uri: http://${config-server-host}:8888
#      name: tools
#      label: master
#      profile: ${spring-protive-active}

logging-level: DEBUG