spring:
  application:
    name: MYALBUM-TOOLS
  redis:
    database: 1
    host: 39.105.137.236
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制
    timeout: 5000 # 连接超时时间（毫秒）
  mail:
    host: smtp.qq.com
    password: vhnfvdgvomxjibce      #你的邮箱授权码
    username: 1243359973@qq.com  # 发送邮件的邮箱地址
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    servlet:
      content-type: text/html


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    time-zone: GMT+8 #时区加8
    default-property-inclusion: non_null  #屏蔽掉为null的字段

  rabbitmq:
    host: 39.105.137.236
    username: admin
    password: admin

#  zipkin:
#    base-url: http://39.105.137.236:9411
#  boot:
#    admin:
#      client:
#        url: http://47.106.199.167:8084

server:
  port: 10030

eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

  instance:
    hostname: 127.0.0.1
    # 优先使用IP地址方式进行注册服务
    #    prefer-ip-address: true
    # 配置使用指定IP
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.hostname}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env #必须排除env文件

feign:
  hystrix:
    enabled: true

#全局配置
# 请求连接的超时时间 默认的时间为 1 秒
ribbon:
  ReadTimeout: 15000 #获取或设置读取操作未完成时发生超时之前的毫秒数
  ConnectTimeout: 15000 #客户端等待与服务器建立连接的时间（以毫秒计）
#  MaxAutoRetries: 1  #在同一台服务器上重试的最大次数
#  MaxAutoRetriesNextServer: 2 #要重试的下一个服务器的最大数量
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 7200000 #断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试。

security:
  oauth2:
    resource:
      id: MYALBUM-USER
      user-info-uri: http://localhost:10000/auth/auth/user
      prefer-token-info: false
myalbum:
  zuulPerfix: TOOLS

#白名单设置
security_whitelist: /**
