spring:
  application:
    name: MYALBUM-SERVICE-GATEWAY
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    time-zone: GMT+8 #时区加8
    default-property-inclusion: non_null  #屏蔽掉为null的字段
#    gateway:
#      discovery:
#        locator:
#          enabled: true
  zipkin:
    base-url: http://39.105.137.236:9411
  boot:
    admin:
      client:
        url: 47.106.199.167

#------------------------eureka-------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.106.199.167:8761/eureka/
  instance:
    hostname: 39.105.137.236
    # 优先使用IP地址方式进行注册服务
    #    prefer-ip-address: true
    # 配置使用指定IP
    ip-address: 39.105.137.236
    instance-id: ${eureka.instance.hostname}:${server.port}
#------------------------Zuul-------------
zuul:
  routes:
    myalbum-service-consumer-test:
      path: /test/**
      serviceId: myalbum-service-consumer-test
      sensitiveHeaders: "*"
    myalbum-service-register:
      path: /reg/**
      serviceId: myalbum-service-register
      sensitiveHeaders: "*"
    myalbum-service-security-oauth2:
      path: /auth/**
      serviceId: myalbum-service-security-oauth2
      sensitiveHeaders: "*"
  retryable: false
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 6000
  add-proxy-headers: true

server:
  port: 10000

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env #必须排除env文件

logging:
  level:
    org.springframework.cloud.gateway: debug

security:
  oauth2:
    client:
      access-token-uri: http://39.105.137.236:${server.port}/auth/oauth/token
      user-authorization-uri: http://39.105.137.236:${server.port}/auth/oauth/authorize
      client-id: client
      client-secret: secret
    resource:
      user-info-uri:  http://39.105.137.236:${server.port}/auth/auth/user
      prefer-token-info: false
#----------------------超时配置-------------------
ribbon:
  ReadTimeout: 10000 #获取或设置读取操作未完成时发生超时之前的毫秒数
  ConnectTimeout: 1000 #客户端等待与服务器建立连接的时间（以毫秒计）
  MaxAutoRetries: 2  #在同一台服务器上重试的最大次数
  MaxAutoRetriesNextServer: 4 #要重试的下一个服务器的最大数量

feign:
  sentinel:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 144000 #断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试。
